// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4.DataDB;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(PmsDatabaseContext))]
    partial class PmsDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication4.DataDB.Attd", b =>
                {
                    b.Property<int>("AttdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ATTD_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttdId"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("Emp_ID");

                    b.Property<int>("Holiday")
                        .HasColumnType("int");

                    b.Property<int>("nd")
                        .HasColumnType("int")
                        .HasColumnName("nd");

                    b.Property<int>("St")
                        .HasColumnType("time")
                        .HasColumnName("ST");

                    b.Property<int>("Tr")
                        .HasColumnType("time")
                        .HasColumnName("TR");

                    b.HasKey("AttdId");

                    b.HasIndex(new[] { "EmpId" }, "IX_ATTD");

                    b.ToTable("ATTD", (string)null);
                });

            modelBuilder.Entity("WebApplication4.DataDB.Dd", b =>
                {
                    b.Property<int>("DdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DD_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DdId"), 1L, 1);

                    b.Property<string>("Ddname")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("DDName")
                        .IsFixedLength();

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("DdId");

                    b.ToTable("DD", (string)null);
                });

            modelBuilder.Entity("WebApplication4.DataDB.EmpInfo", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Emp_ID");

                    b.Property<int>("DdId")
                        .HasColumnType("int")
                        .HasColumnName("DD_ID");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LName");

                    b.Property<string>("Mname")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MName")
                        .IsFixedLength();

                    b.Property<int>("PagibigNo")
                        .HasColumnType("int")
                        .HasColumnName("PAGIBIG_NO");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("Position_ID");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("SssNo")
                        .HasColumnType("int")
                        .HasColumnName("SSS_NO");

                    b.HasKey("EmpId");

                    b.HasIndex("DdId");

                    b.HasIndex("PositionId");

                    b.ToTable("Emp_INFO", (string)null);
                });

            modelBuilder.Entity("WebApplication4.DataDB.P", b =>
                {
                    b.Property<int>("PsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PS_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PsId"), 1L, 1);

                    b.Property<int>("AttdId")
                        .HasColumnType("int")
                        .HasColumnName("ATTD_ID");

                    b.Property<int>("DdId")
                        .HasColumnType("int")
                        .HasColumnName("DD_ID");

                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("Emp_ID");

                    b.HasKey("PsId");

                    b.HasIndex(new[] { "EmpId" }, "IX_PS")
                        .IsUnique();

                    b.HasIndex(new[] { "DdId" }, "IX_PS_1")
                        .IsUnique();

                    b.HasIndex(new[] { "AttdId" }, "IX_PS_2")
                        .IsUnique();

                    b.ToTable("PS", (string)null);
                });

            modelBuilder.Entity("WebApplication4.DataDB.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Position_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"), 1L, 1);

                    b.Property<string>("Position1")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("Position")
                        .IsFixedLength();

                    b.HasKey("PositionId")
                        .HasName("PK_Position_ID");

                    b.ToTable("Position", (string)null);
                });

            modelBuilder.Entity("WebApplication4.DataDB.SysAcc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("sys_acc", (string)null);
                });

            modelBuilder.Entity("WebApplication4.DataDB.EmpInfo", b =>
                {
                    b.HasOne("WebApplication4.DataDB.Dd", "Dd")
                        .WithMany("EmpInfos")
                        .HasForeignKey("DdId")
                        .IsRequired()
                        .HasConstraintName("FK_Emp_INFO_DD");

                    b.HasOne("WebApplication4.DataDB.Attd", "Emp")
                        .WithOne("EmpInfo")
                        .HasForeignKey("WebApplication4.DataDB.EmpInfo", "EmpId")
                        .HasPrincipalKey("WebApplication4.DataDB.Attd", "EmpId")
                        .IsRequired()
                        .HasConstraintName("FK_Emp_INFO_ATTD");

                    b.HasOne("WebApplication4.DataDB.P", "EmpNavigation")
                        .WithOne("EmpInfo")
                        .HasForeignKey("WebApplication4.DataDB.EmpInfo", "EmpId")
                        .HasPrincipalKey("WebApplication4.DataDB.P", "EmpId")
                        .IsRequired()
                        .HasConstraintName("FK_Emp_INFO_PS");

                    b.HasOne("WebApplication4.DataDB.Position", "PositionNavigation")
                        .WithMany("EmpInfos")
                        .HasForeignKey("PositionId")
                        .IsRequired()
                        .HasConstraintName("FK_Emp_INFO_Position");

                    b.Navigation("Dd");

                    b.Navigation("Emp");

                    b.Navigation("EmpNavigation");

                    b.Navigation("PositionNavigation");
                });

            modelBuilder.Entity("WebApplication4.DataDB.Attd", b =>
                {
                    b.Navigation("EmpInfo");
                });

            modelBuilder.Entity("WebApplication4.DataDB.Dd", b =>
                {
                    b.Navigation("EmpInfos");
                });

            modelBuilder.Entity("WebApplication4.DataDB.P", b =>
                {
                    b.Navigation("EmpInfo");
                });

            modelBuilder.Entity("WebApplication4.DataDB.Position", b =>
                {
                    b.Navigation("EmpInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
